repos:
  # Functionality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
  # Disable until a stable version of type annotation is out.
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.770
  #   hooks:
  #     - id: mypy
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        args: [--py3-plus]
  # Docker Lint
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]
  # Style
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
  #  Disable until we are done documenting the code base.
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 5.1.1
  #   hooks:
  #     - id: pydocstyle
  #       args: [--convention=numpy]
