dist: xenial
sudo: required
language: python

python:
- 3.6

before_install:
- bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
- sudo apt-get -q install -y git-annex-standalone

install:
- pip install datalad
- pip freeze

script:
- python tests/create_tests.py
- pytest tests/
