dist: xenial
sudo: required
language: python

python:
- 3.6

git:
  submodules: false
  depth: 1

before_install:
- git clone --depth=1 --branch=master https://github.com/CONP-PCNO/conp-dataset.git ../conp-dataset-master
- bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
- sudo apt-get -q install -y git-annex-standalone

install:
- pip install datalad
- pip freeze
- datalad install -r .
- datalad install -r ../conp-dataset-master
- git config --global diff.renames 0
- git diff --no-index --name-only . ../conp-dataset-master > tests/diff.txt || true
- sed -i '\?^/dev/null?d' ./tests/diff.txt

script:
- find . -name config.sh | xargs bash
- python tests/create_tests.py
- PYTHONPATH=$PWD pytest tests/
