dist: xenial
sudo: required
language: python

python:
- 3.6

git:
  submodules: false

before_install:
- bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
- sudo apt-get -q install -y git-annex-standalone

install:
- pip install datalad html2markdown
- pip install -r scripts/dats_validator/requirements.txt
- pip freeze
- datalad install -r .

script:
- find . -name config.sh | xargs bash
- python tests/create_tests.py
- PYTHONPATH=$PWD pytest tests/
