name: Docker build and push.

on:
  push:
    paths:
      - "projects/**"
      - "tests/**"
    branches:
      - master

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
